apprt/gtk: use a subtitle to mark the current working directory
ghostty-org/ghostty pull request #3570
Opened 2024-12-27 20:43 UTC by tristan957

If the title is already the current working directory, hide the subtitle. Otherwise show the current working directory, like if a command is running for instance.

This is a re-opening of my original PR because I had to delete my fork and re-fork it.

2025-01-02 18:45 UTC, gpanders commented
This is a nice touch, but are there any plans to make this optional?

Fish sets the window title to my current working directory, but in a "condensed" form, so e.g. `/home/ganders/src/ghostty` is `~/s/ghostty`. But since this string doesn't match the pwd exactly, I see this:

![image](https://github.com/user-attachments/assets/fa847a3a-950b-4030-b22b-5c3025dade45)

This is obviously redundant and so just ends up adding visual noise that's unhelpful.

Disabling fish's title setting is not really a good option either, since then I wouldn't have those titles in the tab titles (where the subtitle isn't present).

2025-01-02 18:48 UTC, tristan957 commented
Yeah we can make this optional. Do you have a preferred setting name? `gtk-cwd-subtitle`?

2025-01-02 18:50 UTC, gpanders commented
>In theory, we could make it free-form using an strftime like interface.

I had the same thought, which would also make disabling it easy (just leave it empty). But longer term that would allow it to show not only PWD, but also things like current running command (using shell integration) or hostname (using OSC 7).

2025-01-02 18:55 UTC, tristan957 commented
Maybe, I should shoot for the moon, and just add something like that in this PR. What kind of syntax should we choose? Probably something like `"{cwd}: {hostname} {{these are escaped}}"?

2025-01-02 19:04 UTC, jcollie commented
> Maybe, I should shoot for the moon, and just add something like that in this PR. What kind of syntax should we choose? Probably something like `"{cwd}: {hostname} {{these are escaped}}"?

I wonder how soon we'll get a request to have `{time} {date}`?. Actually, NGL, I'd probably use something like that.

2025-01-02 20:07 UTC, mitchellh requested changes
I'm ready to get merging on this one, thanks for sticking with me. My final request is that this be optional. I'm willing to default it to true for now and see how it feels on my day to day usage but I think as @gpanders noted an option to turn this off would be good.

I would suggest `window-subtitle` and make it an `enum { false, @"working-directory" }`. This will let us add more in the future if we want. It also lets us make it cross-platform in the future if we want. And an enum is forward compatible to a `union(enum)` if we ever want to introduce a formatted string as this PR comment notes.

2025-01-02 21:04 UTC, FantomeBeignet commented
> > Maybe, I should shoot for the moon, and just add something like that in this PR. What kind of syntax should we choose? Probably something like `"{cwd}: {hostname} {{these are escaped}}"?
> 
> I wonder how soon we'll get a request to have `{time} {date}`?. Actually, NGL, I'd probably use something like that.

That's kinda what I requested in #4096

2025-01-02 22:34 UTC, tristan957 commented
> I would suggest `window-subtitle` and make it an `enum { false, @"working-directory" }`. This will let us add more in the future if we want. It also lets us make it cross-platform in the future if we want. And an enum is forward compatible to a `union(enum)` if we ever want to introduce a formatted string as this PR comment notes.

I almost feel like instead of `working-directory`, it would be better to see something like `{working-directory}`, and just make it super future proof, but I'm obviously more than happy to defer :smile:.

2025-01-02 22:36 UTC, mitchellh commented
> I almost feel like instead of working-directory, it would be better to see something like {working-directory}, and just make it super future proof, but I'm obviously more than happy to defer 😄.

I think enums are going to be a lot simpler (and type safe for free) to add new values for. Then we can use this enum later to also build up the format strings. At least that's what I'm thinking. I'm also not 100% sold on the format string yet so this lets us get this merged more quickly rather than combining two features in one PR.

2025-01-03 00:43 UTC, tristan957 commented
Thanks for coming in with a great counter-example @gpanders!

2025-01-03 00:48 UTC, tristan957 commented
I'm not really sure the best way to fix this issue.

```
src/apprt/gtk/notebook_adw.zig:161:21: error: expected type '[:0]const u8', found '[*c]const u8'
    window.setTitle(title);
                    ^~~~~
src/apprt/gtk/Window.zig:431:39: note: parameter type declared here
pub fn setTitle(self: *Window, title: [:0]const u8) void {
                                      ^~~~~~~~~~~~
referenced by:
    init: src/apprt/gtk/notebook_adw.zig:41:86
    init: src/apprt/gtk/notebook.zig:26:61
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src/apprt/gtk/notebook_gtk.zig:260:21: error: expected type '[:0]const u8', found '[*c]const u8'
    window.setTitle(label_text);
                    ^~~~~~~~~~
src/apprt/gtk/Window.zig:431:39: note: parameter type declared here
pub fn setTitle(self: *Window, title: [:0]const u8) void {
```

2025-01-03 01:35 UTC, jcollie commented
> I'm not really sure the best way to fix this issue.
> 
> ```
> src/apprt/gtk/notebook_adw.zig:161:21: error: expected type '[:0]const u8', found '[*c]const u8'
>     window.setTitle(title);
>                     ^~~~~
> src/apprt/gtk/Window.zig:431:39: note: parameter type declared here
> pub fn setTitle(self: *Window, title: [:0]const u8) void {
>                                       ^~~~~~~~~~~~
> referenced by:
>     init: src/apprt/gtk/notebook_adw.zig:41:86
>     init: src/apprt/gtk/notebook.zig:26:61
>     remaining reference traces hidden; use '-freference-trace' to see all reference traces
> src/apprt/gtk/notebook_gtk.zig:260:21: error: expected type '[:0]const u8', found '[*c]const u8'
>     window.setTitle(label_text);
>                     ^~~~~~~~~~
> src/apprt/gtk/Window.zig:431:39: note: parameter type declared here
> pub fn setTitle(self: *Window, title: [:0]const u8) void {
> ```

`std.mem.span` will take a `[*c]u8` as returned from a C function and convert it to a `[:0]u8`. It's used a few places in the GTK apprt.

2025-01-03 05:11 UTC, tristan957 commented on src/config/Config.zig
> +@"window-subtitle": WindowSubtitle = .false,
I made the default false. Easier for me to just enable than make a whole bunch of people disable :smile:

2025-01-03 05:12 UTC, mitchellh commented on src/config/Config.zig
> +@"window-subtitle": WindowSubtitle = .false,
I'm happy to reassess "zero config defaults" as more feedback arrives when something is shipped. I'm very supportive of the least impactful config being the default to start, and if we find many people are turning it on then we switch course.

2025-01-03 05:41 UTC, jcollie approved these changes

2025-01-08 18:10 UTC, merged