gtk: implement dropping files and strings
ghostty-org/ghostty pull request #4211
Opened 2024-12-31 18:32 UTC by jcollie

This allows dropping files and strings onto Ghostty in the GTK apprt. If you drop files onto Ghostty it will be pasted as a list of `file://` URIs. If you drop a string onto Ghostty it will paste the string. Normal rules for pasting (bracketed pasts, unsafe pastes) apply.

Note, there seem to be some oddities with how Firefox and Chrome (and Chrome-based Electron apps) do drag and drop as I haven't been able to get those working yet.

2025-01-01 19:40 UTC, jcollie commented
Note, there seem to be some oddities with how Firefox and Chrome (and Chrome-based Electron apps) do drag and drop as I haven't been able to get those working yet. Firefox and/or GTK seems to be broken because I can't drag a text selection from Firefox to the Gnome Text Editor either.

2025-01-02 22:39 UTC, mitchellh requested changes
Let me know when you want a further review.

2025-01-02 22:39 UTC, mitchellh commented on src/apprt/gtk/Surface.zig
> +pub fn ShellEscapeWriter(comptime T: type) type {
I'd like to see this moved out of the `apprt/gtk` package and somewhere else with a good set of unit tests.

"Somewhere else" is probably `src/terminal`?

2025-01-02 22:43 UTC, jcollie commented on src/apprt/gtk/Surface.zig
> +pub fn ShellEscapeWriter(comptime T: type) type {
Yeah I stuck it there for convenience but I agree that it should be elsewhere, maybe `src/os/shell.zig` since it's kinda "shell" related.

2025-01-02 22:43 UTC, mitchellh commented on src/apprt/gtk/Surface.zig
> +pub fn ShellEscapeWriter(comptime T: type) type {
Agree with that location.

2025-01-07 00:04 UTC, tristan957 commented on src/apprt/gtk/Surface.zig
> +fn g_value_holds(value_: ?*c.GValue, g_type: c.GType) bool {
It might be nice to document that this is equivalent to `G_VALUE_HOLDS`

2025-01-07 00:12 UTC, jcollie commented on src/apprt/gtk/Surface.zig
> +    log.info("drop at {d}×{d}", .{ x, y });
Probably shouldn't, I had it that way for testing. I'll remove it.

2025-01-07 00:18 UTC, tristan957 commented on src/apprt/gtk/Surface.zig
> +        c.gdk_file_list_get_type(),
No biggie, thanks!

2025-01-07 00:19 UTC, tristan957 commented
From my perspective this looks good to go.

2025-01-07 00:49 UTC, jcollie commented on src/apprt/gtk/Surface.zig
> +fn g_value_holds(value_: ?*c.GValue, g_type: c.GType) bool {
Done.

2025-01-07 00:49 UTC, jcollie commented on src/apprt/gtk/Surface.zig
> +    log.info("drop at {d}×{d}", .{ x, y });
Done.

2025-01-07 00:50 UTC, jcollie commented
OK, this should be ready to go!

2025-01-08 18:46 UTC, mitchellh requested changes
One easy request but otherwise looks great. Thanks!

2025-01-08 18:46 UTC, mitchellh commented on src/os/shell.zig
> +pub fn ShellEscapeWriter(comptime T: type) type {
Docs for this please

2025-01-08 21:12 UTC, merged