Add background image support for OpenGL
ghostty-org/ghostty pull request #4226
Opened 2024-12-31 22:28 UTC by yunusey

Partially fixes #3645.

https://github.com/user-attachments/assets/8d61e979-3cad-481a-81fc-bc8a3f8a9573

_I apologize for the image quality - GitHub limits videos to be less than 10MB._

This PR adds support for setting background image dynamically for OpenGL only. Metal still needs its own implementation.

Because the only way to read the image data and decode to RGB/RGBA so that it is ready to be uploaded to the GPU is to use `kitty.terminal.graphics` with the project's current state, we only support PNG.

2025-01-01 03:57 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    // Bind our background image program
The Zig way to deal with optionals in a situation like this is to "strip" the optional like this:

```
const current_background_image = self.current_background_image orelse return;
```
Then you can refer to `current_background_image` without needing the awkward `.?` syntax.

2025-01-01 04:00 UTC, jcollie commented on src/renderer/OpenGL.zig
> +            .ready => {},
I'd recommend:
```
if (self.current_background_image) |current_background_image| {
  switch (current_background_image) {
```

2025-01-01 04:14 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    defer loading.deinit(self.alloc);
Probably not in this commit, but the graphics loading code should be factored out of the kitty graphics code as it's pretty awkward to use here. We can also add JPEG support.

2025-01-01 05:12 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    // Bind our background image program
Oops, thanks for catching that! I will fix it!

2025-01-01 05:15 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    defer loading.deinit(self.alloc);
I agree! I just didn't want to implement a whole system for that - wanted to make sure that this is what we want to do. And I totally agree that we should add JPEG support - it is very crucial!

2025-01-01 18:50 UTC, ShivamRawat0l approved these changes

2025-01-02 04:41 UTC, jcollie requested changes
This is starting to look very good! I'm sure others will have more to say about the rendering code as they have more experience, but I like it!

![Screenshot From 2025-01-01 21-32-10](https://github.com/user-attachments/assets/fe9cd36d-e89a-40d6-af32-8b5a62d25a56)

2025-01-02 04:41 UTC, jcollie commented on src/renderer/opengl/BackgroundImageProgram.zig
> +};
This should be moved up a directory level so that I can be shared with the Metal renderer.

2025-01-02 04:41 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    defer loading.deinit(self.alloc);
Hmm looking at this, we really don't want to drag the Kitty image protocol code into this. The PNG decoding code we have is pretty simple to use, it's basically just:

```
const wuffs = @import("wuffs");
const pngdata = <read data>;
const imgdata = try wuffs.png.decode(allocator, pngdata);
```
You'll end up with a struct that has the image height, width and data in RGBA format which I think is what the OpenGL code is expecting anyway.

I pushed PR #4250 which adds JPEG decoding support so that should soon be available.

2025-01-02 04:41 UTC, jcollie commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
This should not be a `RepeatablePath` as only one image can ever be shown.

2025-01-02 04:51 UTC, yunusey commented on src/renderer/opengl/BackgroundImageProgram.zig
> +};
I will work on the first one; I think you are completely right, it doesn't make any sense for the mode to be defined there (I was just following `ImageProgram`'s implementation, but we are dealing with different things here, so it should be moved to an upper level module).

For the second one, I was planning to add more modes. It is just that the issue says, for the first version, we need the image to be scaled, and I didn't want to take initiative before getting more insight, but I will try implementing them now.

2025-01-02 04:51 UTC, yunusey commented on src/config/Config.zig
> +
Nice catch, will do!

2025-01-02 05:00 UTC, yunusey commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
I also thought about the type we should use for `background-image`. Since, currently, all the config keys related to a path are handled with `RepeatablePath`, I just followed the patterns. What would be your recommendation to use instead of `RepeatablePath`, `[]u8` directly?

Oh, I didn't know about `wuffs`, I will try using it instead. Thanks a lot for letting me know!

2025-01-02 05:18 UTC, jcollie commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
We probably should have a `Path` struct that basically does the same stuff as `RepeatablePath` except it only allows one path.

2025-01-02 20:48 UTC, yunusey commented on src/renderer/opengl/BackgroundImageProgram.zig
> +};
Done! Check out the new modes below:

## Centered
![Centered](https://github.com/user-attachments/assets/d24da9ce-4720-46fa-b373-8e10f270ed1b)
## Stretched
![Stretched](https://github.com/user-attachments/assets/2c75b8f6-4065-4910-a653-e9c5486434a0)
## Tiled
![Tiled](https://github.com/user-attachments/assets/e3b6c80f-c876-42eb-be8a-5f68bc1784ed)
## Zoomed
![Zoomed](https://github.com/user-attachments/assets/9f02da10-d4bc-4cb6-9329-5f2ec7d4dbf0)

2025-01-02 20:52 UTC, yunusey commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
So, apparently, `Path` is used in `Config.zig` as an enum inside `RepeatablePath`, so I thought I would name it `SinglePath`, but if you have any other recommendations, we can most definitely change its name. Also, I thought it would be better if we defined `BackgroundImageMode` directly in `Config.zig` and pass it to lower modules, but if you think we should define it in `renderer`, we can change it as well.

2025-01-02 20:54 UTC, yunusey commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
And I got rid of `kitty.graphics` stuff - we are using `wuffs` directly, and I think it will be easier for us to integrate `JPEG` with your PR.

2025-01-02 21:11 UTC, jcollie requested changes

2025-01-02 21:11 UTC, jcollie commented on src/config/Config.zig
> +
This should be an optional and default to null.

2025-01-02 21:11 UTC, jcollie commented on src/config/Config.zig
> +
This looks good, except that you need to check for SinglePath here:

https://github.com/ghostty-org/ghostty/blob/600e4171544f2ed29ba7a95afe1a10bde51b0030/src/config/Config.zig#L3055-L3074

2025-01-02 21:11 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    var file = std.fs.cwd().openFile(path, .{}) catch |err| {
There should be an assert here checking for an absolute path and then using `std.fs.openFileAbsolute` to open the file.

2025-01-02 21:11 UTC, jcollie commented on src/renderer/shaders/bgimage.f.glsl
> +
I don't know if we can do `#include` in GLSL but if we can we should do that so that the modes never get out of sync between the two files.

2025-01-02 21:11 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    return managed.items;
Don't return `managed.items` directly, return `managed.toOwnedSlice()`.

2025-01-02 21:11 UTC, jcollie commented on src/renderer/OpenGL.zig
> +    reader.readAllArrayList(&managed, size) catch |err| {
It's not necessary to copy `max_image_size` to a new variable.

2025-01-02 21:13 UTC, jcollie commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
Yep, glad you were able to get rid of that.

2025-01-02 21:13 UTC, jcollie commented on src/config/Config.zig
> +@"background-image": RepeatablePath = .{},
> So, apparently, `Path` is used in `Config.zig` as an enum inside `RepeatablePath`, so I thought I would name it `SinglePath`, but if you have any other recommendations, we can most definitely change its name. Also, I thought it would be better if we defined `BackgroundImageMode` directly in `Config.zig` and pass it to lower modules, but if you think we should define it in `renderer`, we can change it as well.

That all makes sense.

2025-01-02 21:41 UTC, yunusey commented on src/config/Config.zig
> +
Done!

2025-01-02 21:41 UTC, yunusey commented on src/config/Config.zig
> +
Sorry for the oversight, done!

2025-01-02 21:41 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    var file = std.fs.cwd().openFile(path, .{}) catch |err| {
Done!

2025-01-02 21:44 UTC, yunusey commented on src/renderer/shaders/bgimage.f.glsl
> +
Unfortunately, I don't think that is possible. You can see another application [here](https://github.com/ghostty-org/ghostty/blob/f60068eabd94e6784f3b557c7287c49dd36bb24c/src/renderer/shaders/cell.f.glsl#L27C1-L31C36).

2025-01-02 21:44 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    return managed.items;
Done!

2025-01-02 21:45 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    reader.readAllArrayList(&managed, size) catch |err| {
Oops, thanks for noticing that!

2025-01-02 22:24 UTC, yunusey commented on src/renderer/shaders/bgimage.f.glsl
> +
I've checked the shader code again, and I don't think we actually need to pass `mode` to the fragment shader. Though this might change in the case of the addition of new image modes that require the fragment shader to access this variable.

2025-01-02 22:45 UTC, mitchellh requested changes
Fantastic work. I've left some review comments but overall this is looking good.

2025-01-02 22:45 UTC, mitchellh commented on src/config/Config.zig
> +    pub fn expand(
Given the duplication here with `RepeatablePath`, I'd like to see this pulled out to a shared common function. It'll probably require some parameter changes. This is especially necessary since we just merged home path expansion and this is now missing it.

2025-01-02 22:45 UTC, mitchellh commented on src/config/Config.zig
> +pub const BackgroundImageMode = enum(u8) {
Please add to docs why this has to be a `u8` and note that these values must always match our shaders exactly.

2025-01-03 03:18 UTC, yunusey commented on src/config/Config.zig
> +    pub fn expand(
Done!

2025-01-03 03:23 UTC, jcollie approved these changes
This is looking good to me!

2025-01-03 03:32 UTC, yunusey commented on src/config/Config.zig
> +pub const BackgroundImageMode = enum(u8) {
I've added a note both for the shader code and for the definition of the `BackgroundImageMode` regarding the synchronization and the use of `u8`.

2025-01-06 17:13 UTC, r0wdiggity commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
would it be possible to add an image position offset? it might make sense as parameters to to the `centered mode` (i.e `centered 1 -1` would move the image 1 in the positive x direction and -1 in the y direction based on the units in the shader)

2025-01-06 17:21 UTC, jcollie commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
It would be _possible_ but it would make the config parser more complex for certain. I'd suggest for now convert your image to a PNG and extend the image with a transparent border on the sides opposite to the way you want to shift the image.

It could be useful to have options to anchor the image in the corners, so `upper_left`, `upper_right`, `lower_left`, `lower_right`.

2025-01-06 17:29 UTC, r0wdiggity commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
yeah thats what I currently have for kitty, but the aspect ratio of the actual image gets messed up because it scales the border as well. The `window_icon` in kitty has the anchors you mentioned which are awesome but using that makes the image appear in each pane with split panes. thanks for the response and the work on this feature!

2025-01-06 17:38 UTC, jcollie commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
`centered` should not alter the aspect ratio of the image, at least as I imagined it. I'd have to double-check the code.

2025-01-06 19:11 UTC, yunusey commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
Okay, I've implemented anchor options as well. You can check them out now. Here are some demos using

## Centered
![2025-01-06-140639_hyprshot](https://github.com/user-attachments/assets/6b8af2d7-30ea-495a-8d56-be59cc9dd18b)
## Upper Left
![2025-01-06-140648_hyprshot](https://github.com/user-attachments/assets/d707bbee-03b6-4dbe-b2b9-191a724b11a8)
## Upper Right
![2025-01-06-140654_hyprshot](https://github.com/user-attachments/assets/bf66d303-54f9-44ed-8713-5dc25fdd728a)
## Lower Right
![2025-01-06-140700_hyprshot](https://github.com/user-attachments/assets/0565350a-ff8e-4300-8c51-72082df4f220)
##  Lower Left
![2025-01-06-140707_hyprshot](https://github.com/user-attachments/assets/504c1a1b-ac5d-4815-95d1-26a2e53cd028)

2025-01-06 19:33 UTC, jcollie approved these changes, later dismissed

2025-01-06 21:33 UTC, r0wdiggity commented on src/config/Config.zig
> +///   * `centered` - Image is centered in the window and displayed 1-to-1 pixel
this looks good thank you!

2025-01-12 23:04 UTC, yunusey commented
@mitchellh, could you take a look at this? Are there any other changes needed here, or is it ready to go?

2025-01-18 08:52 UTC, Rohit-Bevinahally commented on src/config/Config.zig
> +const BackgroundImageProgram = @import("../renderer/opengl/BackgroundImageProgram.zig");
Is this import needed ?

2025-01-18 17:24 UTC, yunusey commented on src/config/Config.zig
> +const BackgroundImageProgram = @import("../renderer/opengl/BackgroundImageProgram.zig");
Thanks for pointing that out! I removed it.

2025-01-19 05:56 UTC, jarodtaylor commented
Ohhhh I can't wait for this to get in!

2025-01-31 21:12 UTC, sagg0t commented
Amazing work here, thank you very much!

And though it's kinda late to ask for such changes may I suggest another option for background-image-mode.
The reason being is that of all the modes implemented so far, if I want an image to fill my whole screen, I'm pretty much choosing between "scaled" mode, which deforms the image or "zoomed" mode, which leaves parts of the window uncovered by the image. And I personally don't find any of those aesthetically pleasing.

The way it should work is that the image is placed in the center, scaled to fill all the window background while preserving aspect ratio, and if the aspect ratio of the image doesn't match one of the terminal window, the part of the image that exceeds the window gets cut off (maybe name it "cropped" mode.)

For reference I can suggest MacOS wallpaper modes:
- "zoomed" mode would be "Fit to Screen";
- "scaled" mode would be "Stretch to Fill Screen";
- and what I'm suggesting is "Fill screen".

I know it's a lot and I'd gladly implement it myself, but I'm barely familiar with Zig and have zero experience with shaders.
So please consider.

2025-02-01 03:37 UTC, yunusey commented
> Amazing work here, thank you very much!

Thank you so much!

> And though it's kinda late to ask for such changes may I suggest another option for background-image-mode. The reason being is that of all the modes implemented so far, if I want an image to fill my whole screen, I'm pretty much choosing between "scaled" mode, which deforms the image or "zoomed" mode, which leaves parts of the window uncovered by the image. And I personally don't find any of those aesthetically pleasing.
> 
> The way it should work is that the image is placed in the center, scaled to fill all the window background while preserving aspect ratio, and if the aspect ratio of the image doesn't match one of the terminal window, the part of the image that exceeds the window gets cut off (maybe name it "cropped" mode.)

I think that's a pretty nice mode. I've just implemented it, and as you requested, the mode's name is `cropped`. In order to use it, assuming you are on MacOS from your comment, you will probably need to wait until the same feature is implemented for Metal, which MacOS uses. @Rohit-Bevinahally probably will take care of that as well!

Here is a video demonstrating how the mode acts when the terminal is resized:

https://github.com/user-attachments/assets/c2b5df39-954d-4fc9-8404-7bf325756af4

_The video quality is pretty bad, but hope is sufficient for demonstration purposes._



> I know it's a lot and I'd gladly implement it myself, but I'm barely familiar with Zig and have zero experience with shaders.
> So please consider.

Thanks a lot for commenting again, I think it is a pretty nice feature!

2025-05-15 14:49 UTC, pluiedev requested changes

2025-05-15 14:49 UTC, pluiedev commented on src/config/Config.zig
> +///     preserving the aspect ratio.
I would recommend using more standardized terminology like `fit`, `contain`, `cover`, etc. from CSS's [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property

2025-05-15 14:49 UTC, pluiedev commented on src/config/Config.zig
> +/// Expand a relative path to an absolute path. This function is used by
Needs to be rebased to use configpkg.Path

2025-05-15 14:49 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +        if (std.mem.eql(u8, ext_lower, ".png")) {
Use `std.ascii.eqlIgnoreCase` to avoid allocation

2025-05-15 14:49 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +            => try self.current_background_image.?.upload(self.alloc),
Why not just use the `current_background_image` that's already been extracted via the if-capture?

2025-05-15 14:49 UTC, pluiedev commented on src/renderer/opengl/BackgroundImageProgram.zig
> +    }, .static_draw);
Nit: you could use a triangle strip here to save 2 vertices (and really, avoid using an EBO entirely)

2025-05-22 23:11 UTC, yunusey commented on src/config/Config.zig
> +///     preserving the aspect ratio.
I think this makes sense, would you mind, maybe, writing what each one should be mapped to? For instance, what should `upper-left` be mapped to in such format? I was also thinking perhaps we could use [Kitty's layout modes](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.background_image_layout).

2025-05-22 23:11 UTC, yunusey commented on src/config/Config.zig
> +/// Expand a relative path to an absolute path. This function is used by
Done!

2025-05-22 23:13 UTC, yunusey commented on src/renderer/OpenGL.zig
> +            self.background_image.value != null)
Thanks for catching that, done!

2025-05-22 23:15 UTC, yunusey commented on src/renderer/OpenGL.zig
> +        if (std.mem.eql(u8, ext_lower, ".png")) {
Thanks for catching that! I don't even know what I was thinking; allocating space to lower down a string only to compare it with another string is pretty crazy 😅

2025-05-22 23:17 UTC, yunusey commented on src/renderer/OpenGL.zig
> +            => try self.current_background_image.?.upload(self.alloc),
So, the issue is that `current_background_image` is `const`. Hence, we can't really call the `upload` function with `current_background_image`. If we capture it as a pointer, it will only complicate things for no need.

2025-05-22 23:23 UTC, qwerasd205 commented on src/renderer/opengl/BackgroundImageProgram.zig
> +    }, .static_draw);
This is how it is in all the current OpenGL shaders but is something I actually fix in my rework (which is... getting close to finished finally)

2025-05-23 02:21 UTC, yunusey commented on src/renderer/opengl/BackgroundImageProgram.zig
> +    }, .static_draw);
As @qwerasd205 also pointed out, this is how we are handling the shaders at the moment (see [ImageProgram](https://github.com/ghostty-org/ghostty/blob/a2f52b08e5ad43420aab4e5cf5b2733cefb05845/src/renderer/opengl/ImageProgram.zig#L58C1-L61C22)). I think it is better if we keep it consistent for now.

2025-05-23 04:29 UTC, pluiedev commented on src/config/Config.zig
> +///     preserving the aspect ratio.
That would be [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position) in CSS land I think, as a separate attribute from fit/contain/cover. FWIW I don't think we need to implement options that are as complex as CSS's, but it's nice to have as a reference.

2025-05-23 04:56 UTC, yunusey commented on src/renderer/opengl/BackgroundImageProgram.zig
> +    }, .static_draw);
@pluiedev, I am marking this as resolved, but if you have any suggestions, don't hesitate to let me know!

2025-05-23 04:58 UTC, yunusey commented on src/renderer/OpenGL.zig
> +            => try self.current_background_image.?.upload(self.alloc),
Can I mark this as resolved?

2025-05-24 04:06 UTC, yunusey commented on src/config/Config.zig
> +///     preserving the aspect ratio.
Okay, so this is how I changed it:
* `zoomed`: `contain`
* `stretched`: `fill`
* `cropped`: `cover`
* `upper-left`: `top-left`
* `upper-right`: `top-right`
* `lower-left`: `bottom-left`
* `lower-right`: `bottom-right`

_I have to say that switching to `top/bottom` from `upper/lower` was a great idea! Apparently, that's what we are using for most other stuff (e.g. [`resize_overlay_position`](https://github.com/ghostty-org/ghostty/blob/26a42fac0ec8f612a3ddce60bab9842c79a2756a/src/config/Config.zig#L1476C1-L1488C61)). Thanks for the suggestion!_

So, for the `tiled` and `centered`;
*  `tiled` doesn't have any mode corresponding to it, unless I am mistaken, so leaving it unchanged for now.
* we could set `centered` to be `none`, but I think it makes it confusing a little bit, we could rename it to `center` like `resize_overlay_position`, or just leave it this way. Please let me know what you think!

2025-05-24 08:25 UTC, pluiedev requested changes

2025-05-24 08:29 UTC, pluiedev commented on src/config/Config.zig
> +///     preserving the aspect ratio.
I personally think that we should split this into two settings. Right now as you can see in the GLSL code, the positions and `centered` don't really make sense when put parallel to the other options, because they *imply* `contain` while putting the image at an offset. Instead, we should have one `background-image-fit` setting that has `contain`, `fill`, `cover` and `tiled`, and a `background-image-position` setting.

We should allow users to position their background in the four cardinal directions too, I think. In the future we could also add pixel/percentage offsets to the setting, but I think 8 directions + center works fine for now

2025-05-24 18:54 UTC, yunusey commented on src/config/Config.zig
> +pub const SinglePath = struct {
This was added prior to the introduction of the `Path` struct (see https://github.com/ghostty-org/ghostty/pull/4226#discussion_r1900534393), and I didn't know that we had this addition. I've made the necessary changes with https://github.com/ghostty-org/ghostty/pull/4226/commits/50cf2fee6acb0eee9f557738011e32633b9cf09f.

2025-05-24 19:52 UTC, yunusey commented on src/config/Config.zig
> +///     preserving the aspect ratio.
Okay, I've implemented this feature with https://github.com/ghostty-org/ghostty/pull/4226/commits/624a8c812ce98209a4c260f3c3979b3a4990782c. Now, we have support for `contain`, `fill`, `cover`, `none`, and `tiled` as `background-image-mode`s and we have support for all the 9 directions with `background-image-position`s. `fill` doesn't get affected from the change in directions, naturally. And when the mode `tiled` is selected, it starts tiling from `top-left` regardless as it has a different mechanism and `top-center` or `center-left` doesn't make sense in this context at all. But `contain`, `cover`, and `none` respect the `background-image-position` setting. Let me know what you think!

2025-05-31 01:06 UTC, cschar commented
Cannot wait for this!

2025-05-31 16:01 UTC, yunusey commented
Hi @pluiedev, did you get a chance to check the recent changes?

2025-05-31 16:56 UTC, pluiedev commented
I'm on vacation right now but I'll check whenever I have time

2025-06-01 20:58 UTC, pluiedev requested changes

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +        const background_image = try config.@"background-image".?.clone(alloc);
Why is this using `.?`? Looks like it will just crash whenever the user doesn't specify a background image

```suggestion
        const background_image = if (config.@"background-image") |v| try v.clone(alloc) else null;
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +                };
I think it's better to flip this logic and use `required` instead

```suggestion
                const img_path, const required = switch (background_image) {
                    .optional => |path| .{ path, false },
                    .required => |path| .{ path, true },
                };
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +                };
```suggestion
                self.prepBackgroundImage(img_path) catch |err| switch (err) {
                    error.InvalidData => if (!optional) {
                        log.err("error loading background image {s}: {}", .{ img_path, err });
                    },
                    else => return err,
                };
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    // Decode the png (currently, we only support png)
Aren't we also parsing jpegs below?

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    errdefer self.alloc.free(data);
I'm slightly confused as to why this is necessary. We own the data contained within `decoded_image` and we're using the same allocator, so why are we making a copy of it and freeing the old data?

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    }
Why must this be a regular file? The user could use a symlink and it would be a perfectly valid use case, especially if they use something like Nix to manage dotfiles. As long as we can get data out of it, it's fine IMO. Directories are already filtered out by `openFileAbsolute` when the `directory` flag is unset anyway.

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    return managed.toOwnedSlice();
This is just [`Reader.readAllAlloc`](https://ziglang.org/documentation/master/std/#std.io.GenericReader.readAllAlloc)

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +            => try self.current_background_image.?.upload(self.alloc),
I still feel I'm a tad allergic to `.?`s. Sorry.

```suggestion
            => try current_background_image.upload(self.alloc),
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +        switch (current_background_image) {
```suggestion
    if (self.current_background_image) |*current_background_image| {
        switch (current_background_image.*) {
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +                self.current_background_image.?.deinit(self.alloc);
```suggestion
                current_background_image.deinit(self.alloc);
```

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/shaders/bgimage.v.glsl
> +		// If zoomed, we want to scale the image to fit the terminal
Comments need updating

2025-06-01 20:58 UTC, pluiedev commented on src/renderer/shaders/bgimage.v.glsl
> +	offset = ((terminal_size * (1.0 - scale)) / 2.0) * vec2(x_pos, y_pos);
Why not just declare the variable here directly? This isn't C

```suggestion
	vec2 offset = ((terminal_size * (1.0 - scale)) / 2.0) * vec2(x_pos, y_pos);
```

2025-06-01 23:24 UTC, yunusey commented on src/renderer/OpenGL.zig
> +        const background_image = try config.@"background-image".?.clone(alloc);
Thanks for catching this.

2025-06-01 23:31 UTC, yunusey commented on src/renderer/OpenGL.zig
> +                };
I've updated it, but just in case you are curious, we are using the other way around [here](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/config/Config.zig#L2829C1-L2832C11), [here](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/renderer/shadertoy.zig#L27C1-L30C11), or [here](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/apprt/gtk/App.zig#L1232C1-L1235C11). So, I had implemented it using `optional` as it was more common than the `required` implementation.

2025-06-01 23:32 UTC, yunusey commented on src/renderer/OpenGL.zig
> +                };
Done.

2025-06-01 23:32 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    // Decode the png (currently, we only support png)
Yes, thanks for catching that.

2025-06-01 23:38 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    assert(std.fs.path.isAbsolute(path));
`openFileAbsolute` already asserts that the path is absolute

2025-06-01 23:43 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    }
I was trying to keep things as similar to [`kitty.graphics_image` implementation](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/terminal/kitty/graphics_image.zig#L239C1-L248C10) as possible, but I've changed it so that we are completely ignoring any of these checks.

2025-06-01 23:43 UTC, yunusey commented on src/renderer/OpenGL.zig
> +            => try self.current_background_image.?.upload(self.alloc),
Done.

2025-06-01 23:44 UTC, yunusey commented on src/renderer/OpenGL.zig
> +        switch (current_background_image) {
Done.

2025-06-01 23:44 UTC, yunusey commented on src/renderer/shaders/bgimage.v.glsl
> +		// If zoomed, we want to scale the image to fit the terminal
Thanks for pointing that out.

2025-06-01 23:45 UTC, yunusey commented on src/renderer/shaders/bgimage.v.glsl
> +	offset = ((terminal_size * (1.0 - scale)) / 2.0) * vec2(x_pos, y_pos);
We used to have an offset that changed based on different modes, so it must have stayed from then. Thanks for pointing that out. Done!

2025-06-01 23:46 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    return managed.toOwnedSlice();
Again, I was trying to keep things as similar to [kitty's implementation](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/terminal/kitty/graphics_image.zig#L260C1-L267C11) as possible, but I've changed it.

2025-06-01 23:46 UTC, yunusey commented on src/renderer/OpenGL.zig
> +                self.current_background_image.?.deinit(self.alloc);
Done.

2025-06-01 23:48 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    }
The thing is that Kitty's implementation has different ["transmission mediums"](https://sw.kovidgoyal.net/kitty/graphics-protocol/#the-transmission-medium) and the code you're copying from deals with only the "simple file" case, which explicitly forbids anything other than regular files. Make sure to check the context!

2025-06-01 23:50 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +    return managed.toOwnedSlice();
In that case it's because we need to be able to *add* data onto an existing pile, because Kitty's image data is streamed and chunked. Again ***please*** make sure to read the surrounding context before blindly copying anything

2025-06-01 23:58 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    }
I see, thank you for pointing that out. I apologize for my oversight.

2025-06-02 00:02 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    assert(std.fs.path.isAbsolute(path));
You are right, https://github.com/ghostty-org/ghostty/pull/4226/commits/5f849b2060f0539db1da327bfb43a86c8f2cb02d removes the redundant `assert`.

2025-06-02 00:04 UTC, yunusey commented on src/renderer/OpenGL.zig
> +    errdefer self.alloc.free(data);
https://github.com/ghostty-org/ghostty/pull/4226/commits/5f849b2060f0539db1da327bfb43a86c8f2cb02d removes the allocation and uses `@constCast` to pass the already owned `decoded_image.data`.

2025-06-02 00:13 UTC, pluiedev approved these changes
Thank you so much for putting up with my BS. I'll let someone more qualified to comment on the quality of the shader code, but the Zig part looks great now. Thanks again!

2025-06-02 00:13 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +        .data = @constCast(decoded_image.data).ptr,
This *looks* very sus, but it should be fine. Honestly I don't know why our wuffs bindings return the decoded data as a `[]const u8` as we in fact own its backing memory, so it should be fine to treat it as a `[]u8` for all intents and purposes...

2025-06-02 00:17 UTC, yunusey commented
> Thank you so much for putting up with my BS. I'll let someone more qualified to comment on the quality of the shader code, but the Zig part looks great now. Thanks again!

Haha, no BS at all! I appreciate all the feedback you provided; let me know if you have any other suggestions!

2025-06-02 00:25 UTC, yunusey commented on src/renderer/OpenGL.zig
> +        .data = @constCast(decoded_image.data).ptr,
> This _looks_ very sus

I agree :)



> Honestly I don't know why our wuffs bindings return the decoded data as a `[]const u8` as we in fact own its backing memory, so it should be fine to treat it as a `[]u8` for all intents and purposes...

I am not really sure either. It looks like both `wuffs.png.decode` and `wuffs.jpeg.decode` have the data as `[]u8`, but for some reason, `ImageData.data` is declared to be `const[] u8` and hence they are cast as `const`. But as far as the safety is concerned, I think it should be fine.

2025-06-02 00:27 UTC, pluiedev requested changes

2025-06-02 00:27 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +                self.prepBackgroundImage(img_path) catch |err| switch (err) {
Oops... I think you forgot to expand paths here. Currently using a path relative to home (prefixed with `~/`) crashes the app 😅

2025-06-02 00:28 UTC, mitchellh commented
FYI I’ve been holding off on this and the cursor animation PRs because I don’t want to make any renderer changes until Qwers refactor is in. After that we should be able to rebase and I’m happy to take that on. 

Until then I’m holding off review for a moment

2025-06-02 00:32 UTC, pluiedev commented
![image](https://github.com/user-attachments/assets/f42cd817-dcf0-4cfe-83c3-9fcc2f6863a6)

The current rendering of the image is also way too dark for some reason. It's supposed to be the same image as my desktop wallpaper:

![image](https://github.com/user-attachments/assets/82d3b124-d714-4c49-a6fc-e09e9b685834)

2025-06-02 01:28 UTC, yunusey commented on src/renderer/OpenGL.zig
> +                self.prepBackgroundImage(img_path) catch |err| switch (err) {
Thanks for pointing that out; it is really interesting. I think `Config.expandPaths` should handle all of these. I'll look into it in a few hours!

2025-06-02 01:29 UTC, yunusey commented
> The current rendering of the image is also way too dark for some reason. It's supposed to be the same image as my desktop wallpaper:

Oh, I am only now noticing the issue (I was testing with `background-image-opacity = 0.4` all the time). Thank you so much for letting me know.

2025-06-02 01:43 UTC, yunusey commented on src/renderer/OpenGL.zig
> +                self.prepBackgroundImage(img_path) catch |err| switch (err) {
So, I think I found the issue: as you know, we are using `?Path` for `background-image` which is not handled in the `Config.expandPath` function. So, we need an additional check for this type. Can you check https://github.com/ghostty-org/ghostty/pull/4226/commits/3784f84c30ad8f6c92341c45b51cbde89d682e96 whenever you have time, please?

2025-06-02 04:42 UTC, yunusey commented
https://github.com/ghostty-org/ghostty/pull/4226/commits/304a67c3e21970cbf12da466943d9f93b6c3d389 should resolve the brightness issue of the background images now. I think `wuff.png.decode` and `wuff.jpeg.decode` had been updated recently that basically changed the way the images are stored (the problem starts occurring after the rebase). There exists an `unlinearize` function that's used in [`image.f.glsl`](https://github.com/ghostty-org/ghostty/blob/1ff91625981ef92add92624c01b6b9095c365ed1/src/renderer/shaders/image.f.glsl#L9C1-L16C2) that converts the image to the `sRGB` with gamma compression that outputs the appropriate colors needed, and I think it solves the issue!

2025-06-02 13:02 UTC, pluiedev commented on src/renderer/OpenGL.zig
> +        .data = @constCast(decoded_image.data).ptr,
Honestly we should just change the type in the wuffs binding to be `[]u8` then

2025-06-02 13:03 UTC, pluiedev approved these changes
![image](https://github.com/user-attachments/assets/09aaa060-9a4b-4d93-8aa8-9a9c9bbab18f)

Gorgeous

2025-06-02 17:13 UTC, yunusey commented on src/renderer/OpenGL.zig
> +        .data = @constCast(decoded_image.data).ptr,
> Honestly we should just change the type in the wuffs binding to be `[]u8` then

Hi again! I think (https://github.com/ghostty-org/ghostty/pull/4226/commits/5034880dde13dcb55966c8e5b12af261dbe34216) should fix the issue now.

2025-06-25 19:25 UTC, qwerasd205 commented
This PR is superseded by #7686. Thanks for the work on this though! Even if this won't be merged, the bike shedding of the config options in particular helped me decide on what config options to provide pretty quickly instead of having to work it out from scratch.

Props for dealing with implementing this under the old renderer architecture- seems like it was annoyingly in the weeds because of the lack of abstraction.

2025-06-25 19:25 UTC, closed without merging